# automatically generated by the FlatBuffers compiler, do not modify

# namespace: structure

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EncounterNest8Table(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsEncounterNest8Table(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EncounterNest8Table()
        x.Init(buf, n + offset)
        return x

    # EncounterNest8Table
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EncounterNest8Table
    def TableID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EncounterNest8Table
    def GameVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EncounterNest8Table
    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from structure.EncounterNest8 import EncounterNest8
            obj = EncounterNest8()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EncounterNest8Table
    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EncounterNest8Table
    def EntriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def EncounterNest8TableStart(builder): builder.StartObject(3)
def EncounterNest8TableAddTableID(builder, TableID): builder.PrependUint64Slot(0, TableID, 0)
def EncounterNest8TableAddGameVersion(builder, GameVersion): builder.PrependUint32Slot(1, GameVersion, 0)
def EncounterNest8TableAddEntries(builder, Entries): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(Entries), 0)
def EncounterNest8TableStartEntriesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def EncounterNest8TableEnd(builder): return builder.EndObject()
