# automatically generated by the FlatBuffers compiler, do not modify

# namespace: structure

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NestHoleDistributionReward8Table(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNestHoleDistributionReward8Table(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NestHoleDistributionReward8Table()
        x.Init(buf, n + offset)
        return x

    # NestHoleDistributionReward8Table
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NestHoleDistributionReward8Table
    def TableID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # NestHoleDistributionReward8Table
    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from structure.NestHoleDistributionReward8 import NestHoleDistributionReward8
            obj = NestHoleDistributionReward8()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NestHoleDistributionReward8Table
    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NestHoleDistributionReward8Table
    def EntriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def NestHoleDistributionReward8TableStart(builder): builder.StartObject(2)
def NestHoleDistributionReward8TableAddTableID(builder, TableID): builder.PrependUint64Slot(0, TableID, 0)
def NestHoleDistributionReward8TableAddEntries(builder, Entries): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(Entries), 0)
def NestHoleDistributionReward8TableStartEntriesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def NestHoleDistributionReward8TableEnd(builder): return builder.EndObject()
